name: ShowItem
version: 2.0
main: club.without.dereku.showitem.ShowItem
author: Dereku
mail: [dereku@without.club, dereku@default.im]
commands: 
    show:
        permission: showitem.use
        default: op